import { SignalsTable } from "@/components/signals/SignalsTable";

export const metadata = { title: "Signals — Charon" };

export default function SignalsPage() {
  return (
    <div className="p-4 md:p-6 space-y-4">
      <div>
        <h1 className="text-xl font-bold tracking-tight">Signals Log</h1>
        <p className="text-muted-foreground text-sm mt-0.5">Last 100 trading signals generated by Charon</p>
      </div>
      <SignalsTable />
    </div>
  );
}
